### ISSUE TITLE
Small example files

### ISSUE THREAD

**Issue by LeonAksman** [Inria-Asclepios/simul-atrophy#2]
Hi Bishesh, do you mind adding small examples of atrophy, image and make files so that the simulator can be run on a desktop?

Thanks a lot!
Leon

**Comment by bishesh** [comment]
Hi Leon,
I have added a small example set that can be run on a desktop and updated README accordingly 
(commit: 7e1ce47 )

**Comment by LeonAksman** [comment]
Hi Bishesh, thanks, I see it there. I managed to get a small example of my
own to run as well.
